=== Skgoud33/Xml/XML/content.dtd
<!ELEMENT content (name, registrationnumber)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT registrationnumber (#PCDATA)>
<!ELEMENT employeedetails(empname, empage, empgender, empsalary)>
<!ELEMENT empname (#PCDATA)>
<!ELEMENT empage (#PCDATA)>
<!ELEMENT empgender (#PCDATA)>
<!ELEMENT  empsalary (#PCDATA)>

=== Skgoud33/Xml/XML/task.xml
<?xml-model href="http://" schematypens="http://"?>
<?xml-stylesheet type='text/css' href='tasks.css'?>
<!DOCTYPE books SYSTEM "content.dtd">
<content>
<name>Banda Saikrishna</name>
<registrationnumber>
		123456789
</registrationnumber>
<employeedetails>
<empname>Saikrishna</empname>
<empage>26</empage>
<empgender>Male</empgender>
<empsalary>15000</empsalary>
</employeedetails>
</content>
